#Checked Mods Name List
willMonsterMountBoat = ["minecraft:zombie_villager"]
#Checked Mods Name List
willMonsterNotLeaveBoat = ["minecraft:zombie_villager"]
#Checked Mods Name List
willMonsterNotHitBoat = ["minecraft:zombie_villager", "minecraft:vex", "minecraft:zombie", "minecraft:husk"]

